### PR TITLE
Fix old version split disk upgrading

### PR DESCRIPTION
**Pull request by dbnicholson**
Really fix upgrading a split disk system from 2.3.

https://phabricator.endlessm.com/T13889

### CODE REVIEW

**Comment by dsd** [comment]
Where is `/var/eos-extra-resize` created these days? i can only see the code that creates `/var/eos-extra-resize2`

**Comment by dbnicholson** [comment]
That's the old one that was created in the 2.3 days. Which is what we want (I think) because the current resizer that creates /var/eos-extra-resize2 (bb6337c3, landed it 2.6.0) doesn't need to handle the migration of the mount unit. We could check for either to be safe, though.

**Comment by dsd** [comment]
Seems to make sense to use the old marker then, but perhaps you can point this out in a comment? Apart from that this looks good to me.

**Comment by dbnicholson** [comment]
OK. I updated the first commit to add comments about why that stamp file suffices for checking.

**Pull request merged**
